"""add novel_chapters, chapter_id on segments; drop macro_block_id

Revision ID: 2354371d94ec
Revises: 389f883c6b66
Create Date: 2026-03-19 15:45:43.248388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2354371d94ec'
down_revision: Union[str, Sequence[str], None] = '389f883c6b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'block_index', name='uq_novel_chapter_block')
    )
    op.create_index(op.f('ix_novel_chapters_id'), 'novel_chapters', ['id'], unique=False)
    op.create_index(op.f('ix_novel_chapters_novel_id'), 'novel_chapters', ['novel_id'], unique=False)
    op.add_column('novel_segments', sa.Column('chapter_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_novel_segments_chapter_id'), 'novel_segments', ['chapter_id'], unique=False)
    op.create_foreign_key(None, 'novel_segments', 'novel_chapters', ['chapter_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('novel_segments', 'macro_block_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novel_segments', sa.Column('macro_block_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'novel_segments', type_='foreignkey')
    op.drop_index(op.f('ix_novel_segments_chapter_id'), table_name='novel_segments')
    op.drop_column('novel_segments', 'chapter_id')
    op.drop_index(op.f('ix_novel_chapters_novel_id'), table_name='novel_chapters')
    op.drop_index(op.f('ix_novel_chapters_id'), table_name='novel_chapters')
    op.drop_table('novel_chapters')
    # ### end Alembic commands ###
