"""add novel_moods table and mood_id to novel_segments

Revision ID: 291b8a64b43d
Revises: 7d0f54797a93
Create Date: 2026-03-19 14:38:09.167761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '291b8a64b43d'
down_revision: Union[str, Sequence[str], None] = '7d0f54797a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel_moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'name', name='uq_novel_mood_name')
    )
    op.create_index(op.f('ix_novel_moods_id'), 'novel_moods', ['id'], unique=False)
    op.create_index(op.f('ix_novel_moods_novel_id'), 'novel_moods', ['novel_id'], unique=False)
    op.add_column('novel_segments', sa.Column('mood_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_novel_segments_mood_id'), 'novel_segments', ['mood_id'], unique=False)
    op.create_foreign_key(None, 'novel_segments', 'novel_moods', ['mood_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'novel_segments', type_='foreignkey')
    op.drop_index(op.f('ix_novel_segments_mood_id'), table_name='novel_segments')
    op.drop_column('novel_segments', 'mood_id')
    op.drop_index(op.f('ix_novel_moods_novel_id'), table_name='novel_moods')
    op.drop_index(op.f('ix_novel_moods_id'), table_name='novel_moods')
    op.drop_table('novel_moods')
    # ### end Alembic commands ###
