"""add novel_themes and segment_themes

Revision ID: 389f883c6b66
Revises: 291b8a64b43d
Create Date: 2026-03-19 15:12:55.684937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '389f883c6b66'
down_revision: Union[str, Sequence[str], None] = '291b8a64b43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'name', name='uq_novel_theme_name')
    )
    op.create_index(op.f('ix_novel_themes_id'), 'novel_themes', ['id'], unique=False)
    op.create_index(op.f('ix_novel_themes_novel_id'), 'novel_themes', ['novel_id'], unique=False)
    op.create_table('segment_themes',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('tone', sa.Float(), nullable=False),
    sa.Column('manifestation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['novel_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['novel_themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id', 'theme_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_themes')
    op.drop_index(op.f('ix_novel_themes_novel_id'), table_name='novel_themes')
    op.drop_index(op.f('ix_novel_themes_id'), table_name='novel_themes')
    op.drop_table('novel_themes')
    # ### end Alembic commands ###
