"""replace character_ids with segment_characters join table

Revision ID: 483f2c010d96
Revises: beb49f53cd0a
Create Date: 2026-03-18 21:23:35.147976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '483f2c010d96'
down_revision: Union[str, Sequence[str], None] = 'beb49f53cd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment_characters',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['novel_characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['novel_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id', 'character_id')
    )
    op.drop_column('novel_segments', 'character_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novel_segments', sa.Column('character_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_table('segment_characters')
    # ### end Alembic commands ###
