"""add novel_places table and place_id to novel_segments

Revision ID: 7d0f54797a93
Revises: 483f2c010d96
Create Date: 2026-03-19 14:26:49.513453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7d0f54797a93'
down_revision: Union[str, Sequence[str], None] = '483f2c010d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'name', name='uq_novel_place_name')
    )
    op.create_index(op.f('ix_novel_places_id'), 'novel_places', ['id'], unique=False)
    op.create_index(op.f('ix_novel_places_novel_id'), 'novel_places', ['novel_id'], unique=False)
    op.add_column('novel_segments', sa.Column('place_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_novel_segments_place_id'), 'novel_segments', ['place_id'], unique=False)
    op.create_foreign_key(None, 'novel_segments', 'novel_places', ['place_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'novel_segments', type_='foreignkey')
    op.drop_index(op.f('ix_novel_segments_place_id'), table_name='novel_segments')
    op.drop_column('novel_segments', 'place_id')
    op.drop_index(op.f('ix_novel_places_novel_id'), table_name='novel_places')
    op.drop_index(op.f('ix_novel_places_id'), table_name='novel_places')
    op.drop_table('novel_places')
    # ### end Alembic commands ###
