"""add start_index and end_index to novel_segments

Revision ID: 840a5852922a
Revises: d25191124b86
Create Date: 2026-03-06 16:33:54.652730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '840a5852922a'
down_revision: Union[str, Sequence[str], None] = 'd25191124b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novel_segments', sa.Column('start_index', sa.Integer(), nullable=False))
    op.add_column('novel_segments', sa.Column('end_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novel_segments', 'end_index')
    op.drop_column('novel_segments', 'start_index')
    # ### end Alembic commands ###
