"""add segment_audio table

Revision ID: 93b378247322
Revises: 2354371d94ec
Create Date: 2026-04-04 21:50:28.709683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93b378247322'
down_revision: Union[str, Sequence[str], None] = '2354371d94ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment_audio',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('audio_key', sa.String(length=512), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['novel_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.drop_index(op.f('segment_characters_character_id_idx'), table_name='segment_characters')
    op.drop_index(op.f('segment_themes_theme_id_idx'), table_name='segment_themes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('segment_themes_theme_id_idx'), 'segment_themes', ['theme_id'], unique=False)
    op.create_index(op.f('segment_characters_character_id_idx'), 'segment_characters', ['character_id'], unique=False)
    op.drop_table('segment_audio')
    # ### end Alembic commands ###
