"""add novel_characters table; add character_ids column to novel_segments table

Revision ID: beb49f53cd0a
Revises: 840a5852922a
Create Date: 2026-03-18 20:38:30.753648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'beb49f53cd0a'
down_revision: Union[str, Sequence[str], None] = '840a5852922a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'name', name='uq_novel_character_name')
    )
    op.create_index(op.f('ix_novel_characters_id'), 'novel_characters', ['id'], unique=False)
    op.create_index(op.f('ix_novel_characters_novel_id'), 'novel_characters', ['novel_id'], unique=False)
    op.add_column('novel_segments', sa.Column('character_ids', postgresql.ARRAY(sa.Integer()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novel_segments', 'character_ids')
    op.drop_index(op.f('ix_novel_characters_novel_id'), table_name='novel_characters')
    op.drop_index(op.f('ix_novel_characters_id'), table_name='novel_characters')
    op.drop_table('novel_characters')
    # ### end Alembic commands ###
